apiVersion: v1
kind: Service
metadata:
  name: billing-database
spec:
  clusterIP: None
  selector:
    app: billing-database
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-database
spec:
  serviceName: billing-database
  replicas: 1
  selector:
    matchLabels:
      app: billing-database
  template:
    metadata:
      labels:
        app: billing-database
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: BILLING_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: BILLING_DB_PASS
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: BILLING_DB_NAME
          volumeMounts:
            - name: billing-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: billing-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 1Gi
