apiVersion: v1
kind: Service
metadata:
  name: billing-app
spec:
  selector:
    app: billing-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
spec:
  serviceName: billing-app
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      containers:
        - name: billing-app
          image: mrazem/billing-app:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: BILLING_DB_HOST
              value: billing-database
            - name: BILLING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: BILLING_DB_USER
            - name: BILLING_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: BILLING_DB_PASS
            - name: BILLING_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: billing-db-secret
                  key: BILLING_DB_NAME
            - name: BILLING_PORT
              value: "8080"
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_URL
            - name: QUEUE_NAME
              value: "billing_queue"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
