apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"inventory-app","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"inventory-app"}},"template":{"metadata":{"labels":{"app":"inventory-app"}},"spec":{"containers":[{"env":[{"name":"INVENTORY_DB_HOST","value":"inventory-database"},{"name":"INVENTORY_DB_USER","valueFrom":{"secretKeyRef":{"key":"POSTGRES_USER","name":"inventory-db-secret"}}},{"name":"INVENTORY_DB_PASS","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"inventory-db-secret"}}},{"name":"INVENTORY_DB_NAME","valueFrom":{"secretKeyRef":{"key":"POSTGRES_DB","name":"inventory-db-secret"}}},{"name":"PORT","value":"8080"}],"image":"mrazem/inventory-app:latest","name":"inventory-app","ports":[{"containerPort":8080,"name":"http"}],"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2025-11-28T11:54:29Z"
  generation: 16
  name: inventory-app
  namespace: default
  resourceVersion: "7238"
  uid: ead83fcc-0afb-46c4-bd39-3948a963866c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: inventory-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-02T16:27:43+02:00"
      creationTimestamp: null
      labels:
        app: inventory-app
    spec:
      containers:
      - env:
        - name: INVENTORY_DB_HOST
          value: inventory-database
        - name: INVENTORY_DB_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: inventory-db-secret
        - name: INVENTORY_DB_PASS
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: inventory-db-secret
        - name: INVENTORY_DB_NAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: inventory-db-secret
        - name: PORT
          value: "8080"
        image: mrazem/inventory-app:latest
        imagePullPolicy: Always
        name: inventory-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-11-28T12:15:31Z"
    lastUpdateTime: "2025-11-28T12:56:23Z"
    message: ReplicaSet "inventory-app-5db79ccd98" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-11-28T12:58:00Z"
    lastUpdateTime: "2025-11-28T12:58:00Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 16
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
