apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: inventory-app
          image: mrazem/inventory-app:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            # DB connection settings (what your Node app reads)
            - name: INVENTORY_DB_HOST
              value: inventory-database
            - name: INVENTORY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: POSTGRES_USER
            - name: INVENTORY_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: POSTGRES_PASSWORD
            - name: INVENTORY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: POSTGRES_DB
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-app
spec:
  selector:
    app: inventory-app
  ports:
    - port: 8080
      targetPort: 8080
      name: http
