apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: inventory_user
  POSTGRES_PASSWORD: inventory_password_123
  POSTGRES_DB: inventory_db
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-db-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: billing_user
  POSTGRES_PASSWORD: billing_password_123
  POSTGRES_DB: billing_db
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: default
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: rabbitmq_user
  RABBITMQ_DEFAULT_PASS: rabbitmq_password_123
---

