# Inventory DB secret
apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
type: Opaque
stringData:
  INVENTORY_DB_USER: inventory_user
  INVENTORY_DB_PASS: inventory_pass_123
  INVENTORY_DB_NAME: movies

---
# Billing DB secret
apiVersion: v1
kind: Secret
metadata:
  name: billing-db-secret
type: Opaque
stringData:
  BILLING_DB_USER: billing_user
  BILLING_DB_PASS: billing_pass_123
  BILLING_DB_NAME: orders

---
# RabbitMQ secret
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: rabbitmq_user
  RABBITMQ_DEFAULT_PASS: rabbitmq_pass_123
  # Both billing-app and api-gateway will use this:
  RABBITMQ_URL: amqp://rabbitmq_user:rabbitmq_pass_123@rabbitmq:5672
