# Inventory DB secret
# Inventory DB secret
apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secret
type: Opaque
stringData:
  POSTGRES_USER: inventory_user
  POSTGRES_PASSWORD: inventory_pass_123
  POSTGRES_DB: movies

---
# Billing DB secret
apiVersion: v1
kind: Secret
metadata:
  name: billing-db-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: billing


---
# RabbitMQ secret
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: rabbitmq_user
  RABBITMQ_DEFAULT_PASS: rabbitmq_pass_123
  # Both billing-app and api-gateway will use this:
  RABBITMQ_URL: amqp://rabbitmq_user:rabbitmq_pass_123@rabbitmq:5672
